sensors: 
- sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
## for simulation
  #image_topic: /kinect/depth/image_raw
## for real kinect
  image_topic: /kinect2/hd/image_depth_rect
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5
  shadow_threshold: 1.0
  padding_offset: 0.0
  padding_scale: 10.0
  filtered_cloud_topic: filtered_cloud