ur5:
  hardware_interface:
   joints: driver_arm_joint

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  gripper_controller:
    type: position_controllers/JointPositionController
    joint: driver_arm_joint
    pid: {p: 200, i: 0.01, d: 50}